### ISSUE TITLE
为啥子用四川话讲解视频

### ISSUE THREAD

**Issue by Duncan1115** [happyapplehorse/agere#9]

**Comment by lr-online** [comment]
just for fun

**Comment by ttm1234** [comment]
我最开始以为ai生成的，听了一会儿感觉这味儿太对了。不可能是ai能生成的

**Comment by happyapplehorse** [comment]
1. 我自己的声音我感觉不好听，没得感情。
2. 作为一个江浙沪包邮区的人，我都能听懂，完全没感觉到有很难懂的发音，并且配了字幕，所以我觉得可行。（也许是因为所说的内容我都事先知道，所以能听懂？也许我听多了四川话，已经是半个四川人了？）
3. Isabel说我给你说一下试试，然后就用四川话说了几句，我笑喷了，所以坚决要求她给我配个音。希望让这个有点长的教程不那么枯燥。hǎnd(ér)lér↝
